"""Default grocery and food catalog rows for membership delivery screens."""

SEED_GROCERY_CATEGORIES = [
    {"key": "rice", "name": "Rice", "sort_order": 0},
    {"key": "atta", "name": "Atta", "sort_order": 1},
    {"key": "dal", "name": "Dal", "sort_order": 2},
    {"key": "oil", "name": "Oil", "sort_order": 3},
    {"key": "spices", "name": "Spices", "sort_order": 4},
    {"key": "veg", "name": "Vegetables", "sort_order": 5},
]

SEED_GROCERY_PRODUCTS = [
    {"key": "g1", "category_key": "rice", "name": "Kolam Rice", "unit": "5 kg", "price_label": "₹420"},
    {"key": "g2", "category_key": "rice", "name": "Basmati Rice", "unit": "1 kg", "price_label": "₹180"},
    {"key": "g3", "category_key": "atta", "name": "Chakki Atta", "unit": "5 kg", "price_label": "₹250"},
    {"key": "g4", "category_key": "dal", "name": "Toor Dal", "unit": "1 kg", "price_label": "₹160"},
    {"key": "g5", "category_key": "dal", "name": "Moong Dal", "unit": "1 kg", "price_label": "₹140"},
    {"key": "g6", "category_key": "oil", "name": "Groundnut Oil", "unit": "1 L", "price_label": "₹210"},
    {"key": "g7", "category_key": "spices", "name": "Turmeric Powder", "unit": "200 g", "price_label": "₹55"},
    {"key": "g8", "category_key": "veg", "name": "Seasonal Vegetables Mix", "unit": "1 basket", "price_label": "₹180"},
]

SEED_FOOD_CUISINES = [
    {
        "key": "maharashtrian",
        "name": "Maharashtrian",
        "description": "Home-style thalis, usal, bhakri and more.",
        "sort_order": 0,
    },
    {
        "key": "gujarati",
        "name": "Gujarati",
        "description": "Mild, wholesome meals with roti and dal.",
        "sort_order": 1,
    },
    {
        "key": "south-indian",
        "name": "South Indian",
        "description": "Idli, dosa, sambar and rice meals.",
        "sort_order": 2,
    },
]

SEED_FOOD_MENU = [
    {"key": "f1", "cuisine_key": "maharashtrian", "meal": "Breakfast", "name": "Poha + Tea", "price_label": "₹90"},
    {"key": "f2", "cuisine_key": "maharashtrian", "meal": "Lunch", "name": "Maharashtrian Thali", "price_label": "₹180"},
    {"key": "f3", "cuisine_key": "maharashtrian", "meal": "Dinner", "name": "Bhakri + Bhaji", "price_label": "₹150"},
    {"key": "f4", "cuisine_key": "gujarati", "meal": "Breakfast", "name": "Thepla + Chutney", "price_label": "₹100"},
    {"key": "f5", "cuisine_key": "gujarati", "meal": "Lunch", "name": "Gujarati Thali", "price_label": "₹190"},
    {"key": "f6", "cuisine_key": "gujarati", "meal": "Dinner", "name": "Khichdi + Kadhi", "price_label": "₹140"},
    {"key": "f7", "cuisine_key": "south-indian", "meal": "Breakfast", "name": "Idli Sambar", "price_label": "₹110"},
    {"key": "f8", "cuisine_key": "south-indian", "meal": "Lunch", "name": "Rice Meal", "price_label": "₹170"},
    {"key": "f9", "cuisine_key": "south-indian", "meal": "Dinner", "name": "Dosa Combo", "price_label": "₹160"},
]

SEED_SERVICE_OFFERINGS = [
    {
        "service_slug": "pooja",
        "title": "Satyanarayan Pooja",
        "description": "Full setup with flowers, Prasad and aarti items.",
        "badge": "2 helpers",
        "price_label": "₹2,499",
        "sort_order": 0,
    },
    {
        "service_slug": "pooja",
        "title": "Ganesh Pooja",
        "description": "Home Ganesh pooja with basic materials included.",
        "badge": "1–2 helpers",
        "price_label": "₹1,999",
        "sort_order": 1,
    },
    {
        "service_slug": "pooja",
        "title": "Griha Shanti",
        "description": "Peace and wellbeing pooja for the household.",
        "badge": "2 helpers",
        "price_label": "₹2,999",
        "sort_order": 2,
    },
    {
        "service_slug": "doctor",
        "title": "Dr. Ananya Mehta",
        "description": "14 years · English, Hindi, Marathi",
        "badge": "General Physician",
        "price_label": "Today · 5:30 PM",
        "meta_json": '{"rating":"4.8","reviews":"126","experience":"14 years","languages":"English, Hindi, Marathi","nextSlot":"Today · 5:30 PM"}',
        "sort_order": 0,
    },
    {
        "service_slug": "doctor",
        "title": "Dr. Rohan Patil",
        "description": "18 years · English, Marathi",
        "badge": "Cardiologist",
        "price_label": "Tomorrow · 11:00 AM",
        "meta_json": '{"rating":"4.9","reviews":"88","experience":"18 years","languages":"English, Marathi","nextSlot":"Tomorrow · 11:00 AM"}',
        "sort_order": 1,
    },
    {
        "service_slug": "lab-testing",
        "title": "Complete Blood Count (CBC)",
        "description": "Standard blood panel.",
        "badge": "Lab",
        "price_label": "₹499",
        "sort_order": 0,
    },
    {
        "service_slug": "lab-testing",
        "title": "Lipid Profile",
        "description": "Cholesterol and triglycerides.",
        "badge": "Lab",
        "price_label": "₹699",
        "sort_order": 1,
    },
    {
        "service_slug": "lab-testing",
        "title": "Thyroid (TSH)",
        "description": "Thyroid stimulating hormone.",
        "badge": "Lab",
        "price_label": "₹450",
        "sort_order": 2,
    },
    {
        "service_slug": "lab-testing",
        "title": "HbA1c",
        "description": "Average blood sugar.",
        "badge": "Lab",
        "price_label": "₹550",
        "sort_order": 3,
    },
    {
        "service_slug": "lab-testing",
        "title": "Vitamin D",
        "description": "Vitamin D level check.",
        "badge": "Lab",
        "price_label": "₹899",
        "sort_order": 4,
    },
    {
        "service_slug": "events-trips",
        "title": "Marathi Play — Evening Show",
        "description": "Pickup optional · 2 hr show · drop after",
        "badge": "Theatre",
        "price_label": "₹350 / person",
        "meta_json": '{"kind":"event","when":"Sat, 6 Sep · 6:30 PM","place":"Near home · Cultural hall"}',
        "sort_order": 0,
    },
    {
        "service_slug": "events-trips",
        "title": "Classical Music Morning",
        "description": "Seated concert · light refreshments",
        "badge": "Music",
        "price_label": "₹200 / person",
        "meta_json": '{"kind":"event","when":"Sun, 14 Sep · 10:00 AM","place":"Local auditorium"}',
        "sort_order": 1,
    },
    {
        "service_slug": "events-trips",
        "title": "Lonavala One Day Trip",
        "description": "Bhushi Dam · lunch · evening return · members get first priority",
        "badge": "Outing",
        "price_label": "₹1,800 / person",
        "meta_json": '{"kind":"trip","when":"Sat, 20 Sep · 7:00 AM departure","place":"Fixed departure · AgeWell outing"}',
        "sort_order": 2,
    },
    {
        "service_slug": "events-trips",
        "title": "Private Family Day Outing",
        "description": "Driver + companion support · itinerary on request",
        "badge": "Family",
        "price_label": "Custom costing",
        "meta_json": '{"kind":"trip","when":"Choose your date","place":"Flexible · private-family option"}',
        "sort_order": 3,
    },
    {
        "service_slug": "home-repair",
        "title": "Plumbing",
        "description": "Taps, leaks, bathroom and kitchen plumbing.",
        "badge": "Repair",
        "price_label": "",
        "sort_order": 0,
    },
    {
        "service_slug": "home-repair",
        "title": "Electrical",
        "description": "Switches, lights, fans and wiring checks.",
        "badge": "Repair",
        "price_label": "",
        "sort_order": 1,
    },
    {
        "service_slug": "home-repair",
        "title": "Carpentry",
        "description": "Doors, cabinets, furniture and fittings.",
        "badge": "Repair",
        "price_label": "",
        "sort_order": 2,
    },
    {
        "service_slug": "home-repair",
        "title": "AC Service",
        "description": "AC cleaning, service and cooling issues.",
        "badge": "Repair",
        "price_label": "",
        "sort_order": 3,
    },
    {
        "service_slug": "home-repair",
        "title": "Other",
        "description": "Any other household maintenance support.",
        "badge": "Repair",
        "price_label": "",
        "sort_order": 4,
    },
    {
        "service_slug": "tech-assistance",
        "title": "Mobile issues",
        "description": "Calls, settings, storage and basic phone troubleshooting.",
        "badge": "Tech",
        "price_label": "",
        "sort_order": 0,
    },
    {
        "service_slug": "tech-assistance",
        "title": "App installation",
        "description": "Install or set up WhatsApp, Zoom, food and grocery apps.",
        "badge": "Tech",
        "price_label": "",
        "sort_order": 1,
    },
    {
        "service_slug": "tech-assistance",
        "title": "Electricity / gas bill payments",
        "description": "Help paying utility bills through digital platforms.",
        "badge": "Tech",
        "price_label": "",
        "sort_order": 2,
    },
    {
        "service_slug": "tech-assistance",
        "title": "Ordering on other platforms",
        "description": "Food or grocery orders on external apps with companion help.",
        "badge": "Tech",
        "price_label": "",
        "sort_order": 3,
    },
    {
        "service_slug": "tech-assistance",
        "title": "Other digital help",
        "description": "Similar technology assistance as needed.",
        "badge": "Tech",
        "price_label": "",
        "sort_order": 4,
    },
    {
        "service_slug": "legal",
        "title": "Legal consultation",
        "description": "Speak with AgeWell partner lawyers about wills, property and related matters.",
        "badge": "Legal",
        "price_label": "Support call",
        "sort_order": 0,
    },
    {
        "service_slug": "ca",
        "title": "CA consultation",
        "description": "Tax, investments and financial paperwork with AgeWell CAs.",
        "badge": "Finance",
        "price_label": "Support call",
        "sort_order": 0,
    },
    {
        "service_slug": "transport",
        "title": "Half day driver",
        "description": "Trained driver for half-day outstation travel.",
        "badge": "1–2 people",
        "price_label": "Half day",
        "sort_order": 0,
    },
    {
        "service_slug": "transport",
        "title": "Full day driver",
        "description": "Trained driver for a full day outstation trip.",
        "badge": "3–4 people",
        "price_label": "Full day",
        "sort_order": 1,
    },
    {
        "service_slug": "medicine",
        "title": "Prescription delivery",
        "description": "Upload a prescription and we arrange home delivery.",
        "badge": "Delivery",
        "price_label": "As per bill",
        "sort_order": 0,
    },
    {
        "service_slug": "care-manager",
        "title": "Monthly Care Manager visit",
        "description": "Scheduled monthly check-in and care coordination.",
        "badge": "Visit",
        "price_label": "Included",
        "sort_order": 0,
    },
    {
        "service_slug": "companion",
        "title": "Daily companion visit",
        "description": "Home assistance and company from AgeWell companions.",
        "badge": "Visit",
        "price_label": "Included",
        "sort_order": 0,
    },
]
