"""Default grocery and food catalog rows for membership delivery screens."""

SEED_GROCERY_CATEGORIES = [
    {"key": "rice", "name": "Rice", "sort_order": 0},
    {"key": "atta", "name": "Atta", "sort_order": 1},
    {"key": "dal", "name": "Dal", "sort_order": 2},
    {"key": "oil", "name": "Oil", "sort_order": 3},
    {"key": "spices", "name": "Spices", "sort_order": 4},
    {"key": "veg", "name": "Vegetables", "sort_order": 5},
]

SEED_GROCERY_PRODUCTS = [
    {"key": "g1", "category_key": "rice", "name": "Kolam Rice", "unit": "5 kg", "price_label": "₹420"},
    {"key": "g2", "category_key": "rice", "name": "Basmati Rice", "unit": "1 kg", "price_label": "₹180"},
    {"key": "g3", "category_key": "atta", "name": "Chakki Atta", "unit": "5 kg", "price_label": "₹250"},
    {"key": "g4", "category_key": "dal", "name": "Toor Dal", "unit": "1 kg", "price_label": "₹160"},
    {"key": "g5", "category_key": "dal", "name": "Moong Dal", "unit": "1 kg", "price_label": "₹140"},
    {"key": "g6", "category_key": "oil", "name": "Groundnut Oil", "unit": "1 L", "price_label": "₹210"},
    {"key": "g7", "category_key": "spices", "name": "Turmeric Powder", "unit": "200 g", "price_label": "₹55"},
    {"key": "g8", "category_key": "veg", "name": "Seasonal Vegetables Mix", "unit": "1 basket", "price_label": "₹180"},
]

SEED_FOOD_CUISINES = [
    {
        "key": "maharashtrian",
        "name": "Maharashtrian",
        "description": "Home-style thalis, usal, bhakri and more.",
        "sort_order": 0,
    },
    {
        "key": "gujarati",
        "name": "Gujarati",
        "description": "Mild, wholesome meals with roti and dal.",
        "sort_order": 1,
    },
    {
        "key": "south-indian",
        "name": "South Indian",
        "description": "Idli, dosa, sambar and rice meals.",
        "sort_order": 2,
    },
]

SEED_FOOD_MENU = [
    {"key": "f1", "cuisine_key": "maharashtrian", "meal": "Breakfast", "name": "Poha + Tea", "price_label": "₹90"},
    {"key": "f2", "cuisine_key": "maharashtrian", "meal": "Lunch", "name": "Maharashtrian Thali", "price_label": "₹180"},
    {"key": "f3", "cuisine_key": "maharashtrian", "meal": "Dinner", "name": "Bhakri + Bhaji", "price_label": "₹150"},
    {"key": "f4", "cuisine_key": "gujarati", "meal": "Breakfast", "name": "Thepla + Chutney", "price_label": "₹100"},
    {"key": "f5", "cuisine_key": "gujarati", "meal": "Lunch", "name": "Gujarati Thali", "price_label": "₹190"},
    {"key": "f6", "cuisine_key": "gujarati", "meal": "Dinner", "name": "Khichdi + Kadhi", "price_label": "₹140"},
    {"key": "f7", "cuisine_key": "south-indian", "meal": "Breakfast", "name": "Idli Sambar", "price_label": "₹110"},
    {"key": "f8", "cuisine_key": "south-indian", "meal": "Lunch", "name": "Rice Meal", "price_label": "₹170"},
    {"key": "f9", "cuisine_key": "south-indian", "meal": "Dinner", "name": "Dosa Combo", "price_label": "₹160"},
]

SEED_SERVICE_OFFERINGS = [
    {
        "service_slug": "pooja",
        "title": "Ganesh Pooja",
        "description": "For new beginnings and success",
        "badge": "1–2 helpers",
        "price_label": "₹5,500",
        "meta_json": '{"category":"festival"}',
        "sort_order": 0,
    },
    {
        "service_slug": "pooja",
        "title": "Lakshmi Pooja",
        "description": "Invite prosperity and abundance into your home",
        "badge": "1–2 helpers",
        "price_label": "₹4,500",
        "meta_json": '{"category":"festival"}',
        "sort_order": 1,
    },
    {
        "service_slug": "pooja",
        "title": "Navratri Pooja",
        "description": "Festival worship with complete arrangements",
        "badge": "1–2 helpers",
        "price_label": "₹6,500",
        "meta_json": '{"category":"festival"}',
        "sort_order": 2,
    },
    {
        "service_slug": "pooja",
        "title": "Diwali Lakshmi Pooja",
        "description": "Auspicious Diwali Lakshmi pooja at home",
        "badge": "1–2 helpers",
        "price_label": "₹7,500",
        "meta_json": '{"category":"festival"}',
        "sort_order": 3,
    },
    {
        "service_slug": "pooja",
        "title": "Satyanarayan Pooja",
        "description": "For peace and prosperity",
        "badge": "2 helpers",
        "price_label": "₹3,500",
        "meta_json": '{"category":"regular"}',
        "sort_order": 4,
    },
    {
        "service_slug": "pooja",
        "title": "Griha Shanti",
        "description": "Peace and wellbeing pooja for the household.",
        "badge": "2 helpers",
        "price_label": "₹2,999",
        "meta_json": '{"category":"special"}',
        "sort_order": 5,
    },
    {
        "service_slug": "pooja",
        "title": "Vastu Shanti",
        "description": "Harmonize your home with Vastu rituals",
        "badge": "1–2 helpers",
        "price_label": "₹4,999",
        "meta_json": '{"category":"special"}',
        "sort_order": 6,
    },
    {
        "service_slug": "pooja",
        "title": "Other Pooja (Custom)",
        "description": "Tell us the pooja you need — we will arrange it",
        "badge": "Custom",
        "price_label": "",
        "meta_json": '{"category":"special","quote":"true"}',
        "sort_order": 7,
    },
    {
        "service_slug": "doctor",
        "title": "Dr. Ananya Mehta",
        "description": "14 years · English, Hindi, Marathi",
        "badge": "General Physician",
        "price_label": "Today · 5:30 PM",
        "meta_json": '{"rating":"4.8","reviews":"126","experience":"14 years","languages":"English, Hindi, Marathi","nextSlot":"Today · 5:30 PM"}',
        "sort_order": 0,
    },
    {
        "service_slug": "doctor",
        "title": "Dr. Rohan Patil",
        "description": "18 years · English, Marathi",
        "badge": "Cardiologist",
        "price_label": "Tomorrow · 11:00 AM",
        "meta_json": '{"rating":"4.9","reviews":"88","experience":"18 years","languages":"English, Marathi","nextSlot":"Tomorrow · 11:00 AM"}',
        "sort_order": 1,
    },
    {
        "service_slug": "health-check",
        "title": "Blood pressure (BP)",
        "description": "Included in free monthly vitals check.",
        "badge": "Included",
        "price_label": "Free",
        "sort_order": 0,
    },
    {
        "service_slug": "health-check",
        "title": "Pulse",
        "description": "Included in free monthly vitals check.",
        "badge": "Included",
        "price_label": "Free",
        "sort_order": 1,
    },
    {
        "service_slug": "health-check",
        "title": "SpO₂",
        "description": "Oxygen saturation check.",
        "badge": "Included",
        "price_label": "Free",
        "sort_order": 2,
    },
    {
        "service_slug": "health-check",
        "title": "Temperature",
        "description": "Body temperature check.",
        "badge": "Included",
        "price_label": "Free",
        "sort_order": 3,
    },
    {
        "service_slug": "health-check",
        "title": "Blood sugar",
        "description": "Finger-prick glucose check.",
        "badge": "Included",
        "price_label": "Free",
        "sort_order": 4,
    },
    {
        "service_slug": "health-check",
        "title": "ECG (extra)",
        "description": "Available at additional charges.",
        "badge": "Extra",
        "price_label": "Charges apply",
        "sort_order": 5,
    },
    {
        "service_slug": "health-check",
        "title": "Other paid test",
        "description": "Request any other paid diagnostic test.",
        "badge": "Extra",
        "price_label": "Charges apply",
        "sort_order": 6,
    },
    {
        "service_slug": "monthly-blood-test",
        "title": "Monthly CBC",
        "description": "Complete blood count with home sample collection.",
        "badge": "Included",
        "price_label": "Free",
        "meta_json": '{"kind":"included"}',
        "sort_order": 0,
    },
    {
        "service_slug": "monthly-blood-test",
        "title": "LFT",
        "description": "Liver function test (extra to monthly CBC).",
        "badge": "Extra",
        "price_label": "Charges apply",
        "meta_json": '{"kind":"extra"}',
        "sort_order": 1,
    },
    {
        "service_slug": "monthly-blood-test",
        "title": "KFT",
        "description": "Kidney function test (extra to monthly CBC).",
        "badge": "Extra",
        "price_label": "Charges apply",
        "meta_json": '{"kind":"extra"}',
        "sort_order": 2,
    },
    {
        "service_slug": "monthly-blood-test",
        "title": "Lipid profile",
        "description": "Cholesterol and triglycerides (extra to monthly CBC).",
        "badge": "Extra",
        "price_label": "Charges apply",
        "meta_json": '{"kind":"extra"}',
        "sort_order": 3,
    },
    {
        "service_slug": "monthly-blood-test",
        "title": "Thyroid",
        "description": "Thyroid stimulating hormone (extra to monthly CBC).",
        "badge": "Extra",
        "price_label": "Charges apply",
        "meta_json": '{"kind":"extra"}',
        "sort_order": 4,
    },
    {
        "service_slug": "monthly-blood-test",
        "title": "Urine routine",
        "description": "Urine routine examination (extra to monthly CBC).",
        "badge": "Extra",
        "price_label": "Charges apply",
        "meta_json": '{"kind":"extra"}',
        "sort_order": 5,
    },
    {
        "service_slug": "lab-testing",
        "title": "Complete Blood Count (CBC)",
        "description": "Standard blood panel.",
        "badge": "Lab",
        "price_label": "₹499",
        "sort_order": 0,
    },
    {
        "service_slug": "lab-testing",
        "title": "Lipid Profile",
        "description": "Cholesterol and triglycerides.",
        "badge": "Lab",
        "price_label": "₹699",
        "sort_order": 1,
    },
    {
        "service_slug": "lab-testing",
        "title": "Thyroid (TSH)",
        "description": "Thyroid stimulating hormone.",
        "badge": "Lab",
        "price_label": "₹450",
        "sort_order": 2,
    },
    {
        "service_slug": "lab-testing",
        "title": "HbA1c",
        "description": "Average blood sugar.",
        "badge": "Lab",
        "price_label": "₹550",
        "sort_order": 3,
    },
    {
        "service_slug": "lab-testing",
        "title": "Liver Function Test (LFT)",
        "description": "Liver panel (extra to monthly CBC).",
        "badge": "Extra",
        "price_label": "Charges apply",
        "sort_order": 5,
    },
    {
        "service_slug": "lab-testing",
        "title": "Kidney Function Test (KFT)",
        "description": "Kidney panel (extra to monthly CBC).",
        "badge": "Extra",
        "price_label": "Charges apply",
        "sort_order": 6,
    },
    {
        "service_slug": "lab-testing",
        "title": "Urine Routine",
        "description": "Urine routine examination (extra to monthly CBC).",
        "badge": "Extra",
        "price_label": "Charges apply",
        "sort_order": 7,
    },
    {
        "service_slug": "events-trips",
        "title": "Temple Visit & Morning Walk",
        "description": "Gentle morning walk and temple visit with fellow members nearby.",
        "badge": "Local Event",
        "price_label": "Included",
        "meta_json": '{"kind":"event","when":"15 Sep","place":"Kandivali"}',
        "sort_order": 0,
    },
    {
        "service_slug": "events-trips",
        "title": "Art Exhibition Visit",
        "description": "Guided visit to a local art exhibition with light refreshments.",
        "badge": "Local Event",
        "price_label": "Included",
        "meta_json": '{"kind":"event","when":"18 Sep","place":"Borivali"}',
        "sort_order": 1,
    },
    {
        "service_slug": "events-trips",
        "title": "Yoga in the Park",
        "description": "Outdoor yoga session focused on mobility, balance and calm.",
        "badge": "Local Event",
        "price_label": "Included",
        "meta_json": '{"kind":"event","when":"20 Sep","place":"Kandivali"}',
        "sort_order": 2,
    },
    {
        "service_slug": "events-trips",
        "title": "Lonavala Getaway",
        "description": "Scenic hills escape with companion support for the family.",
        "badge": "Family Tour",
        "price_label": "Charges apply",
        "meta_json": '{"kind":"tour","duration":"2D / 1N","tags":"Nature|Relaxation"}',
        "sort_order": 3,
    },
    {
        "service_slug": "events-trips",
        "title": "Kerala Backwaters",
        "description": "Houseboat stay and peaceful backwater views with AgeWell support.",
        "badge": "Family Tour",
        "price_label": "Charges apply",
        "meta_json": '{"kind":"tour","duration":"4D / 3N","tags":"Scenic|Peaceful"}',
        "sort_order": 4,
    },
    {
        "service_slug": "events-trips",
        "title": "Alibaug Day Trip",
        "description": "Beach and fort day outing with pickup and drop coordination.",
        "badge": "Family Tour",
        "price_label": "Charges apply",
        "meta_json": '{"kind":"tour","duration":"1D","tags":"Beach|Fort"}',
        "sort_order": 5,
    },
    {
        "service_slug": "events-trips",
        "title": "Nashik Spiritual Tour",
        "description": "Temple circuit with companion assistance for senior members.",
        "badge": "Senior Tour",
        "price_label": "Charges apply",
        "meta_json": '{"kind":"senior","when":"10-12 Oct 2026","duration":"3D / 2N","tags":"Spiritual|Group"}',
        "sort_order": 6,
    },
    {
        "service_slug": "events-trips",
        "title": "Statue of Unity",
        "description": "Iconic monument visit with lodging and companion support.",
        "badge": "Senior Tour",
        "price_label": "Charges apply",
        "meta_json": '{"kind":"senior","when":"5-6 Nov 2026","duration":"2D / 1N","tags":"History|Scenic"}',
        "sort_order": 7,
    },
    {
        "service_slug": "events-trips",
        "title": "Goa Leisure Tour",
        "description": "Relaxed coastal break with AgeWell members and companion care.",
        "badge": "Senior Tour",
        "price_label": "Charges apply",
        "meta_json": '{"kind":"senior","when":"12-14 Dec 2026","duration":"3D / 2N","tags":"Beach|Leisure"}',
        "sort_order": 8,
    },
    {
        "service_slug": "home-repair",
        "title": "Plumbing",
        "description": "e.g. leakage, taps, bathroom & kitchen plumbing",
        "badge": "Repair",
        "price_label": "",
        "sort_order": 0,
    },
    {
        "service_slug": "home-repair",
        "title": "Electrical",
        "description": "e.g. lights, fans, switches & wiring",
        "badge": "Repair",
        "price_label": "",
        "sort_order": 1,
    },
    {
        "service_slug": "home-repair",
        "title": "Carpentry",
        "description": "e.g. furniture, doors, cabinets & fittings",
        "badge": "Repair",
        "price_label": "",
        "sort_order": 2,
    },
    {
        "service_slug": "home-repair",
        "title": "AC Service",
        "description": "e.g. cleaning, servicing & cooling repairs",
        "badge": "Repair",
        "price_label": "",
        "sort_order": 3,
    },
    {
        "service_slug": "home-repair",
        "title": "Other Services",
        "description": "e.g. painting, civil work & other maintenance",
        "badge": "Repair",
        "price_label": "",
        "sort_order": 4,
    },
    {
        "service_slug": "banking-companion",
        "title": "Pension Withdrawal",
        "description": "Support requested for monthly pension withdrawal",
        "badge": "Banking",
        "price_label": "Per visit",
        "sort_order": 0,
    },
    {
        "service_slug": "banking-companion",
        "title": "Account Related Help",
        "description": "Balance, statements and account queries",
        "badge": "Banking",
        "price_label": "Per visit",
        "sort_order": 1,
    },
    {
        "service_slug": "banking-companion",
        "title": "KYC Update",
        "description": "Aadhaar and PAN update assistance",
        "badge": "Banking",
        "price_label": "Per visit",
        "sort_order": 2,
    },
    {
        "service_slug": "banking-companion",
        "title": "Passbook Update",
        "description": "Passbook update at nearest branch",
        "badge": "Banking",
        "price_label": "Per visit",
        "sort_order": 3,
    },
    {
        "service_slug": "banking-companion",
        "title": "Cheque Book Request",
        "description": "Request and collect a new cheque book",
        "badge": "Banking",
        "price_label": "Per visit",
        "sort_order": 4,
    },
    {
        "service_slug": "banking-companion",
        "title": "NEFT / RTGS Assistance",
        "description": "Help with fund transfers at the branch",
        "badge": "Banking",
        "price_label": "Per visit",
        "sort_order": 5,
    },
    {
        "service_slug": "banking-companion",
        "title": "Fixed Deposit (FD) Support",
        "description": "Open or renew fixed deposits",
        "badge": "Banking",
        "price_label": "Per visit",
        "sort_order": 6,
    },
    {
        "service_slug": "banking-companion",
        "title": "Other Banking Service",
        "description": "Any other banking related assistance",
        "badge": "Banking",
        "price_label": "Per visit",
        "sort_order": 7,
    },
    {
        "service_slug": "local-transport",
        "title": "Cab Assistance",
        "description": "Companion help booking a comfortable cab for local trips.",
        "badge": "Local",
        "price_label": "",
        "sort_order": 0,
    },
    {
        "service_slug": "local-transport",
        "title": "Rickshaw Assistance",
        "description": "Companion help arranging an auto/rikshaw for short distances.",
        "badge": "Local",
        "price_label": "",
        "sort_order": 1,
    },
    {
        "service_slug": "tech-assistance",
        "title": "Mobile issues",
        "description": "Calls, settings, storage and basic phone troubleshooting.",
        "badge": "Tech",
        "price_label": "",
        "sort_order": 0,
    },
    {
        "service_slug": "tech-assistance",
        "title": "App installation",
        "description": "Install or set up WhatsApp, Zoom, food and grocery apps.",
        "badge": "Tech",
        "price_label": "",
        "sort_order": 1,
    },
    {
        "service_slug": "legal",
        "title": "Property Matters",
        "description": "Guidance on buying, selling, inheritance and more.",
        "badge": "Legal",
        "price_label": "Support call",
        "sort_order": 0,
    },
    {
        "service_slug": "legal",
        "title": "Family & Personal Matters",
        "description": "Support for wills, power of attorney and other personal legal needs.",
        "badge": "Legal",
        "price_label": "Support call",
        "sort_order": 1,
    },
    {
        "service_slug": "legal",
        "title": "Consumer Rights",
        "description": "Advice on fraud, disputes and consumer protection.",
        "badge": "Legal",
        "price_label": "Support call",
        "sort_order": 2,
    },
    {
        "service_slug": "legal",
        "title": "Other Legal Support",
        "description": "Consultations for various legal matters.",
        "badge": "Legal",
        "price_label": "Support call",
        "sort_order": 3,
    },
    {
        "service_slug": "ca",
        "title": "ITR Filing Support",
        "description": "Help with income tax return filing.",
        "badge": "Finance",
        "price_label": "Support call",
        "sort_order": 0,
    },
    {
        "service_slug": "ca",
        "title": "Financial Guidance",
        "description": "Investments, pensions and savings advice.",
        "badge": "Finance",
        "price_label": "Support call",
        "sort_order": 1,
    },
    {
        "service_slug": "ca",
        "title": "Support for CA Services",
        "description": "Documentation, filings and certifications.",
        "badge": "Finance",
        "price_label": "Support call",
        "sort_order": 2,
    },
    {
        "service_slug": "ca",
        "title": "Taxation Queries",
        "description": "General tax questions and clarifications.",
        "badge": "Finance",
        "price_label": "Support call",
        "sort_order": 3,
    },
    {
        "service_slug": "transport",
        "title": "Hatchback",
        "description": "Best for 1-3 people",
        "badge": "1–3 people",
        "price_label": "Distance based",
        "sort_order": 0,
    },
    {
        "service_slug": "transport",
        "title": "Sedan",
        "description": "Best for 3-4 people",
        "badge": "3–4 people",
        "price_label": "Distance based",
        "sort_order": 1,
    },
    {
        "service_slug": "transport",
        "title": "SUV",
        "description": "Best for 4-6 people",
        "badge": "4–6 people",
        "price_label": "Distance based",
        "sort_order": 2,
    },
    {
        "service_slug": "transport",
        "title": "Innova / Crysta",
        "description": "Best for 4-6 people",
        "badge": "4–6 people",
        "price_label": "Distance based",
        "sort_order": 3,
    },
    {
        "service_slug": "transport",
        "title": "Tempo Traveller",
        "description": "Best for 7-12 people",
        "badge": "7–12 people",
        "price_label": "Distance based",
        "sort_order": 4,
    },
    {
        "service_slug": "medicine",
        "title": "Prescription delivery",
        "description": "Upload a prescription and we arrange home delivery.",
        "badge": "Delivery",
        "price_label": "As per bill",
        "sort_order": 0,
    },
    {
        "service_slug": "care-manager",
        "title": "Monthly Care Manager visit",
        "description": "Scheduled monthly check-in and care coordination.",
        "badge": "Visit",
        "price_label": "Included",
        "sort_order": 0,
    },
    {
        "service_slug": "companion",
        "title": "Companion visit (20 / month)",
        "description": "Home assistance or meetup, up to 30 minutes. Always available for emergency.",
        "badge": "Visit",
        "price_label": "Included",
        "sort_order": 0,
    },
    {
        "service_slug": "cctv",
        "title": "Main Door / Entrance",
        "description": "Primary entrance camera for visitors and deliveries. Live view and recordings on the app.",
        "badge": "Online",
        "price_label": "",
        "meta_json": '{"kind":"camera"}',
        "sort_order": 0,
    },
    {
        "service_slug": "cctv",
        "title": "Visitor at Door",
        "description": "Motion alert at main entrance.",
        "badge": "Recording",
        "price_label": "",
        "meta_json": '{"kind":"recording","when":"Today · 9:12 AM","duration":"0:42"}',
        "sort_order": 1,
    },
    {
        "service_slug": "cctv",
        "title": "Delivery Person",
        "description": "Delivery at main entrance.",
        "badge": "Recording",
        "price_label": "",
        "meta_json": '{"kind":"recording","when":"Today · 7:40 AM","duration":"1:15"}',
        "sort_order": 2,
    },
    {
        "service_slug": "cctv",
        "title": "Motion Detected",
        "description": "Motion alert at main entrance.",
        "badge": "Recording",
        "price_label": "",
        "meta_json": '{"kind":"recording","when":"Yesterday · 6:55 PM","duration":"0:28"}',
        "sort_order": 3,
    },
    {
        "service_slug": "cctv",
        "title": "Visitor at Door",
        "description": "Visitor at main entrance.",
        "badge": "Recording",
        "price_label": "",
        "meta_json": '{"kind":"recording","when":"Yesterday · 11:20 AM","duration":"0:55"}',
        "sort_order": 4,
    },
    {
        "service_slug": "home-inspection",
        "title": "August 2026 checkup",
        "description": "Monthly general home safety check.",
        "badge": "Report",
        "price_label": "",
        "meta_json": (
            '{"kind":"report","monthLabel":"August 2026","inspectedOn":"28 Aug 2026",'
            '"overall":"All clear","areasJson":"[{\\"name\\":\\"Washroom\\",\\"status\\":\\"OK\\",'
            '\\"note\\":\\"Non-slip mat in place\\"},{\\"name\\":\\"Bedroom\\",\\"status\\":\\"OK\\",'
            '\\"note\\":\\"Night light working\\"},{\\"name\\":\\"Entrance\\",\\"status\\":\\"OK\\",'
            '\\"note\\":\\"Lock and lighting checked\\"},{\\"name\\":\\"Kitchen\\",\\"status\\":\\"Attention\\",'
            '\\"note\\":\\"Recommend tighter gas hose check next month\\"}]"}'
        ),
        "sort_order": 0,
    },
    {
        "service_slug": "home-inspection",
        "title": "July 2026 checkup",
        "description": "Monthly general home safety check.",
        "badge": "Report",
        "price_label": "",
        "meta_json": (
            '{"kind":"report","monthLabel":"July 2026","inspectedOn":"26 Jul 2026",'
            '"overall":"All clear","areasJson":"[{\\"name\\":\\"Washroom\\",\\"status\\":\\"OK\\",'
            '\\"note\\":\\"Grab bar secure\\"},{\\"name\\":\\"Bedroom\\",\\"status\\":\\"OK\\",'
            '\\"note\\":\\"Clear pathways\\"},{\\"name\\":\\"Entrance\\",\\"status\\":\\"OK\\",'
            '\\"note\\":\\"No hazards\\"}]"}'
        ),
        "sort_order": 1,
    },
    {
        "service_slug": "lab-testing",
        "title": "Tomorrow · 8:00 AM",
        "description": "Home sample collection slot.",
        "badge": "Slot",
        "price_label": "",
        "meta_json": '{"kind":"slot"}',
        "sort_order": 10,
    },
    {
        "service_slug": "lab-testing",
        "title": "Tomorrow · 10:30 AM",
        "description": "Home sample collection slot.",
        "badge": "Slot",
        "price_label": "",
        "meta_json": '{"kind":"slot"}',
        "sort_order": 11,
    },
    {
        "service_slug": "lab-testing",
        "title": "Wed, 3 Sep · 9:00 AM",
        "description": "Home sample collection slot.",
        "badge": "Slot",
        "price_label": "",
        "meta_json": '{"kind":"slot"}',
        "sort_order": 12,
    },
    {
        "service_slug": "lab-testing",
        "title": "Thu, 4 Sep · 11:00 AM",
        "description": "Home sample collection slot.",
        "badge": "Slot",
        "price_label": "",
        "meta_json": '{"kind":"slot"}',
        "sort_order": 13,
    },
    {
        "service_slug": "medical-history",
        "title": "Monthly complete body test",
        "description": "Report uploaded · doctor reviewed",
        "badge": "Blood",
        "price_label": "",
        "meta_json": '{"kind":"record","date":"4 Aug 2026"}',
        "sort_order": 0,
    },
    {
        "service_slug": "medical-history",
        "title": "Lipid Profile",
        "description": "Home sample collection · normal range",
        "badge": "Lab",
        "price_label": "",
        "meta_json": '{"kind":"record","date":"12 Jul 2026"}',
        "sort_order": 1,
    },
    {
        "service_slug": "medical-history",
        "title": "GP consultation note",
        "description": "Continue current medication · review in 30 days",
        "badge": "Notes",
        "price_label": "",
        "meta_json": '{"kind":"record","date":"12 Jul 2026"}',
        "sort_order": 2,
    },
    {
        "service_slug": "medical-history",
        "title": "Dr. Mehta prescription",
        "description": "BP and cholesterol medicines",
        "badge": "Prescriptions",
        "price_label": "",
        "meta_json": '{"kind":"record","date":"12 Jul 2026"}',
        "sort_order": 3,
    },
    {
        "service_slug": "medical-history",
        "title": "Influenza vaccine",
        "description": "Annual flu shot recorded",
        "badge": "Immunizations",
        "price_label": "",
        "meta_json": '{"kind":"record","date":"20 May 2026"}',
        "sort_order": 4,
    },
    {
        "service_slug": "medical-history",
        "title": "Monthly complete body test",
        "description": "Report + suggestion on file",
        "badge": "Blood",
        "price_label": "",
        "meta_json": '{"kind":"record","date":"4 Jul 2026"}',
        "sort_order": 5,
    },
    {
        "service_slug": "events-trips",
        "title": "Spiritual",
        "description": "Temple visits, spiritual gatherings and faith-based programs.",
        "badge": "Interest",
        "price_label": "",
        "meta_json": '{"kind":"interest"}',
        "sort_order": 20,
    },
    {
        "service_slug": "events-trips",
        "title": "Music",
        "description": "Concerts, classical music and cultural performances.",
        "badge": "Interest",
        "price_label": "",
        "meta_json": '{"kind":"interest"}',
        "sort_order": 21,
    },
    {
        "service_slug": "events-trips",
        "title": "Nature",
        "description": "Parks, gardens and outdoor nature programs.",
        "badge": "Interest",
        "price_label": "",
        "meta_json": '{"kind":"interest"}',
        "sort_order": 22,
    },
    {
        "service_slug": "events-trips",
        "title": "History",
        "description": "Heritage sites, monuments and historical tours.",
        "badge": "Interest",
        "price_label": "",
        "meta_json": '{"kind":"interest"}',
        "sort_order": 23,
    },
    {
        "service_slug": "events-trips",
        "title": "Food",
        "description": "Food festivals, tastings and culinary outings.",
        "badge": "Interest",
        "price_label": "",
        "meta_json": '{"kind":"interest"}',
        "sort_order": 24,
    },
    {
        "service_slug": "events-trips",
        "title": "Wellness",
        "description": "Yoga, wellness workshops and health programs.",
        "badge": "Interest",
        "price_label": "",
        "meta_json": '{"kind":"interest"}',
        "sort_order": 25,
    },
    {
        "service_slug": "events-trips",
        "title": "Art & Culture",
        "description": "Exhibitions, theatre and cultural events.",
        "badge": "Interest",
        "price_label": "",
        "meta_json": '{"kind":"interest"}',
        "sort_order": 26,
    },
    {
        "service_slug": "events-trips",
        "title": "Shopping",
        "description": "Markets, malls and shopping outings.",
        "badge": "Interest",
        "price_label": "",
        "meta_json": '{"kind":"interest"}',
        "sort_order": 27,
    },
    {
        "service_slug": "events-trips",
        "title": "Social Meetups",
        "description": "Member meetups and social gatherings.",
        "badge": "Interest",
        "price_label": "",
        "meta_json": '{"kind":"interest"}',
        "sort_order": 28,
    },
    {
        "service_slug": "events-trips",
        "title": "Short Trips",
        "description": "Day trips and short getaways nearby.",
        "badge": "Interest",
        "price_label": "",
        "meta_json": '{"kind":"interest"}',
        "sort_order": 29,
    },
    {
        "service_slug": "events-trips",
        "title": "Long Tours",
        "description": "Multi-day tours across Maharashtra and India.",
        "badge": "Interest",
        "price_label": "",
        "meta_json": '{"kind":"interest"}',
        "sort_order": 30,
    },
    {
        "service_slug": "small-errands",
        "title": "Buy Medicines",
        "description": "Pharmacy pickup during companion visit.",
        "badge": "Errand",
        "price_label": "",
        "sort_order": 0,
    },
    {
        "service_slug": "small-errands",
        "title": "Pick up Groceries",
        "description": "Small grocery purchases nearby.",
        "badge": "Errand",
        "price_label": "",
        "sort_order": 1,
    },
    {
        "service_slug": "small-errands",
        "title": "Document Drop / Pickup",
        "description": "Submit or collect papers nearby.",
        "badge": "Errand",
        "price_label": "",
        "sort_order": 2,
    },
    {
        "service_slug": "small-errands",
        "title": "Post Office Visit",
        "description": "Courier, stamps or parcel drop nearby.",
        "badge": "Errand",
        "price_label": "",
        "sort_order": 3,
    },
    {
        "service_slug": "small-errands",
        "title": "Other Small Errand",
        "description": "Any other short nearby task.",
        "badge": "Errand",
        "price_label": "",
        "sort_order": 4,
    },
    {
        "service_slug": "errand-coordination",
        "title": "Ironing",
        "description": "Coordinate ironing service at home.",
        "badge": "Coordinate",
        "price_label": "",
        "sort_order": 0,
    },
    {
        "service_slug": "errand-coordination",
        "title": "Haircut (at home/salon)",
        "description": "Book and coordinate grooming services.",
        "badge": "Coordinate",
        "price_label": "",
        "sort_order": 1,
    },
    {
        "service_slug": "errand-coordination",
        "title": "Home Cleaning",
        "description": "Coordinate home cleaning with a trusted vendor.",
        "badge": "Coordinate",
        "price_label": "",
        "sort_order": 2,
    },
    {
        "service_slug": "errand-coordination",
        "title": "Minor Repairs & Maintenance",
        "description": "Coordinate small home maintenance jobs.",
        "badge": "Coordinate",
        "price_label": "",
        "sort_order": 3,
    },
    {
        "service_slug": "errand-coordination",
        "title": "Other Services",
        "description": "Any other personal service coordination.",
        "badge": "Coordinate",
        "price_label": "",
        "sort_order": 4,
    },
    {
        "service_slug": "cyber-security",
        "title": "Digital Arrest Fraud",
        "description": "Guidance if someone claims police or cyber cell action.",
        "badge": "Security",
        "price_label": "",
        "sort_order": 0,
    },
    {
        "service_slug": "cyber-security",
        "title": "Banking & Payment Fraud",
        "description": "UPI, card and banking scam support.",
        "badge": "Security",
        "price_label": "",
        "sort_order": 1,
    },
    {
        "service_slug": "cyber-security",
        "title": "WhatsApp / Social Media Fraud",
        "description": "Fake profiles, hacked accounts and message scams.",
        "badge": "Security",
        "price_label": "",
        "sort_order": 2,
    },
    {
        "service_slug": "cyber-security",
        "title": "Fake Calls, Messages & Links",
        "description": "Phishing and OTP trap awareness.",
        "badge": "Security",
        "price_label": "",
        "sort_order": 3,
    },
    {
        "service_slug": "cyber-security",
        "title": "Identity Theft & Account Hacking",
        "description": "Help securing accounts after a breach.",
        "badge": "Security",
        "price_label": "",
        "sort_order": 4,
    },
    {
        "service_slug": "cyber-security",
        "title": "What is a Digital Arrest Scam? How to Stay Safe",
        "description": "DIGITAL ARREST SCAM",
        "badge": "YouTube Video",
        "price_label": "",
        "meta_json": '{"kind":"video","duration":"5:28","url":"https://www.youtube.com/results?search_query=digital+arrest+scam"}',
        "sort_order": 5,
    },
    {
        "service_slug": "cyber-security",
        "title": "Beware of Fake Links on WhatsApp",
        "description": "FAKE WHATSAPP LINKS",
        "badge": "YouTube Video",
        "price_label": "",
        "meta_json": '{"kind":"video","duration":"4:12","url":"https://www.youtube.com/results?search_query=fake+whatsapp+link+scam"}',
        "sort_order": 6,
    },
    {
        "service_slug": "cyber-security",
        "title": "Top 10 Cyber Crime Cases in India (2024)",
        "description": "Awareness PDF on notable cyber crime cases.",
        "badge": "PDF",
        "price_label": "",
        "meta_json": '{"kind":"pdf","url":"https://www.google.com/search?q=cyber+crime+cases+india+pdf"}',
        "sort_order": 7,
    },
    {
        "service_slug": "emergency-companion",
        "title": "Hospital Procedure Support",
        "description": "Assistance with admissions, paperwork and coordination",
        "badge": "Feature",
        "price_label": "",
        "meta_json": '{"kind":"feature"}',
        "sort_order": 0,
    },
    {
        "service_slug": "emergency-companion",
        "title": "Dedicated Companion",
        "description": "Stays at hospital for 8-10 hours",
        "badge": "Feature",
        "price_label": "",
        "meta_json": '{"kind":"feature"}',
        "sort_order": 1,
    },
    {
        "service_slug": "emergency-companion",
        "title": "Regular Updates",
        "description": "Keeps your family informed about health condition and discharge",
        "badge": "Feature",
        "price_label": "",
        "meta_json": '{"kind":"feature"}',
        "sort_order": 2,
    },
    {
        "service_slug": "emergency-companion",
        "title": "Peace of Mind",
        "description": "A trusted companion when you need it the most",
        "badge": "Feature",
        "price_label": "",
        "meta_json": '{"kind":"feature"}',
        "sort_order": 3,
    },
    {
        "service_slug": "emergency-companion",
        "title": "8 Hours",
        "description": "Hospital companion coverage for 8 hours.",
        "badge": "Option",
        "price_label": "Based on availability",
        "meta_json": '{"kind":"option"}',
        "sort_order": 10,
    },
    {
        "service_slug": "emergency-companion",
        "title": "10 Hours",
        "description": "Hospital companion coverage for 10 hours.",
        "badge": "Option",
        "price_label": "Based on availability",
        "meta_json": '{"kind":"option"}',
        "sort_order": 11,
    },
    {
        "service_slug": "stool-cleaning",
        "title": "Regular Cleaning",
        "description": "Morning and evening cleaning",
        "badge": "Feature",
        "price_label": "",
        "meta_json": '{"kind":"feature"}',
        "sort_order": 0,
    },
    {
        "service_slug": "stool-cleaning",
        "title": "Hygienic & Safe",
        "description": "Ensures a clean and healthy home environment",
        "badge": "Feature",
        "price_label": "",
        "meta_json": '{"kind":"feature"}',
        "sort_order": 1,
    },
    {
        "service_slug": "stool-cleaning",
        "title": "Professional Support",
        "description": "Trained staff with the right tools and care",
        "badge": "Feature",
        "price_label": "",
        "meta_json": '{"kind":"feature"}',
        "sort_order": 2,
    },
    {
        "service_slug": "stool-cleaning",
        "title": "Comfort & Peace of Mind",
        "description": "So you can focus on what matters most",
        "badge": "Feature",
        "price_label": "",
        "meta_json": '{"kind":"feature"}',
        "sort_order": 3,
    },
    {
        "service_slug": "stool-cleaning",
        "title": "Monthly Plan",
        "description": "Morning + evening stool cleaning & servicing.",
        "badge": "Plan",
        "price_label": "₹22,000 / month",
        "meta_json": '{"kind":"plan"}',
        "sort_order": 10,
    },
    {
        "service_slug": "maid-assistance",
        "title": "Trained Maid",
        "description": "Verified and well-trained staff",
        "badge": "Feature",
        "price_label": "",
        "meta_json": '{"kind":"feature"}',
        "sort_order": 0,
    },
    {
        "service_slug": "maid-assistance",
        "title": "Complete Cleaning",
        "description": "House & utensil cleaning, stock drying",
        "badge": "Feature",
        "price_label": "",
        "meta_json": '{"kind":"feature"}',
        "sort_order": 1,
    },
    {
        "service_slug": "maid-assistance",
        "title": "Hygienic Home",
        "description": "A cleaner and healthier living environment",
        "badge": "Feature",
        "price_label": "",
        "meta_json": '{"kind":"feature"}',
        "sort_order": 2,
    },
    {
        "service_slug": "maid-assistance",
        "title": "More Free Time",
        "description": "So you can focus on what matters most",
        "badge": "Feature",
        "price_label": "",
        "meta_json": '{"kind":"feature"}',
        "sort_order": 3,
    },
    {
        "service_slug": "maid-assistance",
        "title": "Monthly Plan",
        "description": "Trained maid for house & utensil cleaning, stock drying.",
        "badge": "Plan",
        "price_label": "₹6,500 / month",
        "meta_json": '{"kind":"plan"}',
        "sort_order": 10,
    },
    {
        "service_slug": "ayurvedic-massage",
        "title": "Authentic Ayurvedic Care",
        "description": "Based on traditional wellness principles",
        "badge": "Feature",
        "price_label": "",
        "meta_json": '{"kind":"feature"}',
        "sort_order": 0,
    },
    {
        "service_slug": "ayurvedic-massage",
        "title": "Certified Therapists",
        "description": "Trained and experienced professionals",
        "badge": "Feature",
        "price_label": "",
        "meta_json": '{"kind":"feature"}',
        "sort_order": 1,
    },
    {
        "service_slug": "ayurvedic-massage",
        "title": "Relax & Rejuvenate",
        "description": "Helps reduce stress, improve circulation and enhance overall well-being",
        "badge": "Feature",
        "price_label": "",
        "meta_json": '{"kind":"feature"}',
        "sort_order": 2,
    },
    {
        "service_slug": "ayurvedic-massage",
        "title": "At Your Home",
        "description": "Enjoy a professional massage in the comfort and privacy of your home",
        "badge": "Feature",
        "price_label": "",
        "meta_json": '{"kind":"feature"}',
        "sort_order": 3,
    },
    {
        "service_slug": "ayurvedic-massage",
        "title": "45 mins",
        "description": "Ayurvedic massage session at home.",
        "badge": "Option",
        "price_label": "₹1,500",
        "meta_json": '{"kind":"option"}',
        "sort_order": 10,
    },
    {
        "service_slug": "ayurvedic-massage",
        "title": "60 mins",
        "description": "Ayurvedic massage session at home.",
        "badge": "Option",
        "price_label": "₹2,000",
        "meta_json": '{"kind":"option"}',
        "sort_order": 11,
    },
]
