export const adminQueryKeys = {
  all: ['admin'] as const,
  users: (params?: Record<string, unknown>) => ['admin', 'users', params ?? {}] as const,
  user: (id: string) => ['admin', 'users', id] as const,
  seniors: (params?: Record<string, unknown>) => ['admin', 'seniors', params ?? {}] as const,
  senior: (id: string) => ['admin', 'seniors', id] as const,
  careManagers: ['admin', 'careManagers'] as const,
  careManager: (id: string) => ['admin', 'careManagers', id] as const,
  services: ['admin', 'services'] as const,
  serviceRequests: (params?: Record<string, unknown>) => ['admin', 'serviceRequests', params ?? {}] as const,
  visits: (params?: Record<string, unknown>) => ['admin', 'visits', params ?? {}] as const,
  visit: (id: string) => ['admin', 'visits', id] as const,
  visitTasks: (id: string) => ['admin', 'visits', id, 'tasks'] as const,
  visitReports: (id: string) => ['admin', 'visits', id, 'reports'] as const,
  appointments: (params?: Record<string, unknown>) => ['admin', 'appointments', params ?? {}] as const,
  appointment: (id: string) => ['admin', 'appointments', id] as const,
  providers: ['admin', 'providers'] as const,
  memberships: ['admin', 'memberships'] as const,
  membershipPlans: (params?: Record<string, unknown>) => ['admin', 'memberships', 'plans', params ?? {}] as const,
  membershipBenefits: (params?: Record<string, unknown>) => ['admin', 'memberships', 'benefits', params ?? {}] as const,
  membershipRecords: (params?: Record<string, unknown>) => ['admin', 'memberships', 'records', params ?? {}] as const,
  emergencies: (params?: Record<string, unknown>) => ['admin', 'emergencies', params ?? {}] as const,
  emergency: (id: string) => ['admin', 'emergencies', id] as const,
  emergencyEvents: (id: string) => ['admin', 'emergencies', id, 'events'] as const,
  notifications: (params?: Record<string, unknown>) => ['admin', 'notifications', params ?? {}] as const,
  audit: (params?: Record<string, unknown>) => ['admin', 'audit', params ?? {}] as const,
  healthRecords: (seniorId: string) => ['admin', 'health', seniorId] as const,
  membershipCurrent: (seniorId: string) => ['admin', 'memberships', 'current', seniorId] as const,
  membershipUsage: (seniorId: string) => ['admin', 'memberships', 'usage', seniorId] as const,
};
