import type { ComponentType } from 'react';
import {
  Accessibility,
  Ambulance,
  Apple,
  ArrowLeft,
  ArrowRight,
  Award,
  Banknote,
  Bell,
  Bike,
  Building2,
  Broom,
  BroomSparkles,
  BrushCleaning,
  Bus,
  Calculator,
  Calendar,
  CalendarDays,
  CalendarHeart,
  Car,
  Camera,
  Cctv,
  ChartColumn,
  ChartLine,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  CirclePlus,
  CircleUser,
  ClipboardCheck,
  ClipboardList,
  ClipboardPen,
  Clock,
  CloudOff,
  Contact,
  CreditCard,
  Droplets,
  Ellipsis,
  Eye,
  EyeOff,
  File,
  Files,
  FileText,
  Flame,
  FlaskConical,
  Flower2,
  Gavel,
  HandHeart,
  HandHelping,
  Hammer,
  Headphones,
  Heart,
  HeartHandshake,
  HeartPulse,
  Home,
  House,
  Inbox,
  KeyRound,
  Lamp,
  Landmark,
  LayoutGrid,
  Leaf,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  Mic,
  Moon,
  Music,
  Navigation,
  Newspaper,
  PaintRoller,
  Pencil,
  Phone,
  Pill,
  Play,
  Puzzle,
  Route,
  Salad,
  Scale,
  ScanSearch,
  Scissors,
  Search,
  Settings,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Siren,
  Smartphone,
  Snowflake,
  Sparkles,
  Square,
  SquareCheck,
  Stethoscope,
  Laptop,
  TestTube,
  Trash2,
  TriangleAlert,
  User,
  UserPlus,
  Users,
  Utensils,
  Volume2,
  VolumeX,
  Wrench,
  Zap,
} from 'lucide-react-native';

type LucideGlyph = ComponentType<{ size?: number; color?: string; strokeWidth?: number }>;

/**
 * Line-icon catalog (Lucide). Keep names stable so screens can restyle
 * without swapping libraries later.
 */
export const ICONS = {
  'home-outline': Home,
  home: Home,
  house: House,
  'grid-outline': LayoutGrid,
  grid: LayoutGrid,
  'medkit-outline': HeartPulse,
  medkit: HeartPulse,
  'people-outline': Users,
  people: Users,
  'person-outline': User,
  person: User,
  'person-circle-outline': CircleUser,
  'person-add-outline': UserPlus,
  'calendar-outline': Calendar,
  calendar: Calendar,
  'calendar-days': CalendarDays,
  'calendar-star': CalendarHeart,
  'notifications-outline': Bell,
  'time-outline': Clock,
  'chevron-forward': ChevronRight,
  'chevron-down': ChevronDown,
  'chevron-back': ChevronLeft,
  'ellipsis-horizontal': Ellipsis,
  'arrow-back': ArrowLeft,
  'arrow-forward': ArrowRight,
  warning: TriangleAlert,
  'warning-outline': TriangleAlert,
  'alert-circle-outline': CircleAlert,
  ambulance: Ambulance,
  'call-outline': Phone,
  'business-outline': Building2,
  'card-outline': CreditCard,
  'clipboard-outline': ClipboardList,
  'clipboard-text-outline': ClipboardList,
  'clipboard-check': ClipboardCheck,
  /** Care Manager — Lucide has no ClipboardUser in this version; ClipboardPen is closest. */
  'clipboard-user': ClipboardPen,
  'document-text-outline': FileText,
  'document-outline': File,
  'file-document-outline': FileText,
  'file-tray-outline': Inbox,
  'menu-outline': Menu,
  'heart-outline': Heart,
  'heart-handshake': HeartHandshake,
  'key-outline': KeyRound,
  'accessibility-outline': Accessibility,
  'log-out-outline': LogOut,
  'mail-outline': Mail,
  'settings-outline': Settings,
  'search-outline': Search,
  'scan-search': ScanSearch,
  'help-circle-outline': CircleHelp,
  headset: Headphones,
  'ribbon-outline': Award,
  'lock-closed-outline': Lock,
  checkmark: Check,
  'checkmark-circle-outline': CircleCheck,
  navigate: Navigation,
  water: Droplets,
  restaurant: Utensils,
  'restaurant-outline': Utensils,
  car: Car,
  'car-outline': Car,
  route: Route,
  bike: Bike,
  broom: Broom,
  'broom-sparkles': BroomSparkles,
  'brush-cleaning': BrushCleaning,
  'flask-outline': FlaskConical,
  'phone-portrait-outline': Smartphone,
  play: Play,
  'cart-outline': ShoppingCart,
  'shopping-bag': ShoppingBag,
  pill: Pill,
  'test-tube': TestTube,
  doctor: Stethoscope,
  stethoscope: Stethoscope,
  'card-account-phone-outline': Contact,
  bus: Bus,
  music: Music,
  puzzle: Puzzle,
  newspaper: Newspaper,
  'plus-circle': CirclePlus,
  'account-circle': CircleUser,
  'account-plus': UserPlus,
  'shield-checkmark-outline': ShieldCheck,
  'checkbox-outline': SquareCheck,
  'checkbox-blank-outline': Square,
  'create-outline': Pencil,
  'camera-outline': Camera,
  cctv: Cctv,
  'eye-outline': Eye,
  'eye-off-outline': EyeOff,
  'trash-outline': Trash2,
  'cloud-offline-outline': CloudOff,
  location: MapPin,
  siren: Siren,
  sparkles: Sparkles,
  mic: Mic,
  'volume-high': Volume2,
  'volume-mute': VolumeX,
  'chatbubble-outline': MessageCircle,
  landmark: Landmark,
  calculator: Calculator,
  'chart-column': ChartColumn,
  'chart-line': ChartLine,
  wrench: Wrench,
  lamp: Lamp,
  flame: Flame,
  flower: Flower2,
  leaf: Leaf,
  salad: Salad,
  apple: Apple,
  moon: Moon,
  zap: Zap,
  snowflake: Snowflake,
  banknote: Banknote,
  files: Files,
  'hand-heart': HandHeart,
  scale: Scale,
  gavel: Gavel,
  'hand-helping': HandHelping,
  scissors: Scissors,
  laptop: Laptop,
  hammer: Hammer,
  'paint-roller': PaintRoller,
} as const satisfies Record<string, LucideGlyph>;

export type IconName = keyof typeof ICONS;
