import type { ComponentType } from 'react';
import {
  Accessibility,
  Ambulance,
  ArrowLeft,
  ArrowRight,
  Award,
  Bell,
  Bike,
  Building2,
  Bus,
  Calendar,
  CalendarHeart,
  Car,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  CirclePlus,
  CircleUser,
  ClipboardList,
  Clock,
  CloudOff,
  Contact,
  CreditCard,
  Droplets,
  Camera,
  Eye,
  EyeOff,
  File,
  FileText,
  FlaskConical,
  Heart,
  HeartPulse,
  Home,
  Inbox,
  KeyRound,
  LayoutGrid,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Menu,
  Music,
  Navigation,
  Newspaper,
  Pencil,
  Phone,
  Pill,
  Puzzle,
  Search,
  Settings,
  ShieldCheck,
  ShoppingCart,
  Siren,
  Smartphone,
  Sparkles,
  Square,
  SquareCheck,
  Stethoscope,
  TestTube,
  Trash2,
  TriangleAlert,
  User,
  UserPlus,
  Users,
  Utensils,
} from 'lucide-react-native';

type LucideGlyph = ComponentType<{ size?: number; color?: string; strokeWidth?: number }>;

/**
 * Line-icon catalog (Lucide). Keep names stable so screens can restyle
 * without swapping libraries later.
 */
export const ICONS = {
  'home-outline': Home,
  home: Home,
  'grid-outline': LayoutGrid,
  grid: LayoutGrid,
  'medkit-outline': HeartPulse,
  medkit: HeartPulse,
  'people-outline': Users,
  people: Users,
  'person-outline': User,
  person: User,
  'person-circle-outline': CircleUser,
  'person-add-outline': UserPlus,
  'calendar-outline': Calendar,
  calendar: Calendar,
  'calendar-star': CalendarHeart,
  'notifications-outline': Bell,
  'time-outline': Clock,
  'chevron-forward': ChevronRight,
  'chevron-down': ChevronDown,
  'chevron-back': ChevronLeft,
  'arrow-back': ArrowLeft,
  'arrow-forward': ArrowRight,
  warning: TriangleAlert,
  'warning-outline': TriangleAlert,
  'alert-circle-outline': CircleAlert,
  ambulance: Ambulance,
  'call-outline': Phone,
  'business-outline': Building2,
  'card-outline': CreditCard,
  'clipboard-outline': ClipboardList,
  'clipboard-text-outline': ClipboardList,
  'document-text-outline': FileText,
  'document-outline': File,
  'file-document-outline': FileText,
  'file-tray-outline': Inbox,
  'menu-outline': Menu,
  'heart-outline': Heart,
  'key-outline': KeyRound,
  'accessibility-outline': Accessibility,
  'log-out-outline': LogOut,
  'mail-outline': Mail,
  'settings-outline': Settings,
  'search-outline': Search,
  'help-circle-outline': CircleHelp,
  'ribbon-outline': Award,
  'lock-closed-outline': Lock,
  checkmark: Check,
  'checkmark-circle-outline': CircleCheck,
  navigate: Navigation,
  water: Droplets,
  restaurant: Utensils,
  'restaurant-outline': Utensils,
  car: Car,
  'car-outline': Car,
  bike: Bike,
  'flask-outline': FlaskConical,
  'phone-portrait-outline': Smartphone,
  'cart-outline': ShoppingCart,
  pill: Pill,
  'test-tube': TestTube,
  doctor: Stethoscope,
  'card-account-phone-outline': Contact,
  bus: Bus,
  music: Music,
  puzzle: Puzzle,
  newspaper: Newspaper,
  'plus-circle': CirclePlus,
  'account-circle': CircleUser,
  'account-plus': UserPlus,
  'shield-checkmark-outline': ShieldCheck,
  'checkbox-outline': SquareCheck,
  'checkbox-blank-outline': Square,
  'create-outline': Pencil,
  'camera-outline': Camera,
  'eye-outline': Eye,
  'eye-off-outline': EyeOff,
  'trash-outline': Trash2,
  'cloud-offline-outline': CloudOff,
  location: MapPin,
  siren: Siren,
  sparkles: Sparkles,
} as const satisfies Record<string, LucideGlyph>;

export type IconName = keyof typeof ICONS;
